# Generated by Django 5.1.1 on 2024-10-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, default='user_photos/default.jpg', null=True, upload_to='user_photos/'),
        ),
    ]
