# Generated by Django 5.1.1 on 2024-10-04 12:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requiere_patente', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida')], max_length=10)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('PESOS', 'Pesos')], max_length=10)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('patente', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='finanzas/movimientos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.categoria')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.mediopago')),
            ],
        ),
    ]
