# Generated by Django 5.0.3 on 2024-10-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='estado',
        ),
    ]
