# Generated by Django 5.1.1 on 2024-10-12 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, unique=True)),
                ('valor_cotizacion', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='precio_dolar',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='precio_peso',
            field=models.DecimalField(decimal_places=2, default=2, editable=False, max_digits=12),
            preserve_default=False,
        ),
    ]
