# Generated by Django 5.1.1 on 2024-10-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_cotizaciondolar_movimiento_precio_dolar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciondolar',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
