# Generated by Django 5.1.1 on 2024-10-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_mediopago_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediopago',
            name='moneda',
            field=models.CharField(blank=True, choices=[('USD', 'Dólares'), ('PESOS', 'Pesos')], max_length=10, null=True),
        ),
    ]
