# Generated by Django 5.1.1 on 2024-10-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_mediopago_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='documento_adjunto',
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='finanzas/documentos_adjuntos/')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_adjuntos', to='finanzas.movimiento')),
            ],
        ),
    ]
